import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import "./globals.css";

import Link from "next/link";

import { HomeIcon } from "lucide-react";

import { cn } from "@/lib/utils";

import RootLayoutClient from "./layout-client";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          "[&>main]:min-h-[calc(100vh_-_theme(spacing.16))]",
          fontSans.variable
        )}
      >
        <header className="sticky top-0 z-10 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
          <nav className="flex flex-col gap-6 text-lg font-medium md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
            <Link
              href="/"
              className="flex items-center gap-2 text-lg font-semibold md:text-base"
            >
              <HomeIcon className="size-5" />
              <h1>GPU Shop</h1>
            </Link>
            <Link
              href="/products"
              className="text-muted-foreground transition-colors hover:text-foreground"
            >
              Products
            </Link>
            <Link
              href="/users"
              className="text-muted-foreground transition-colors hover:text-foreground"
            >
              Users
            </Link>
          </nav>
        </header>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
